spring:
  application:
    name: java_project

  datasource:
    url: jdbc:mysql://localhost:3306/mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin


  jpa:
    hibernate:
      ddb-auto: update

